// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjW0qLj7eiijAsEgyWDqm1_ZpmZAto2_8',
    appId: '1:379493253637:web:fb47db8d1a65d9b0e3526c',
    messagingSenderId: '379493253637',
    projectId: 'wallia-market',
    authDomain: 'wallia-market.firebaseapp.com',
    storageBucket: 'wallia-market.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkJ0kUh3hZ4rb10nLTkbmnEjWi-ZNeLfY',
    appId: '1:379493253637:android:5c30ec61fb4390e7e3526c',
    messagingSenderId: '379493253637',
    projectId: 'wallia-market',
    storageBucket: 'wallia-market.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZYTXRHSkws7PaRHSbaeWtnJ2Fv5mqs-o',
    appId: '1:379493253637:ios:5e986932621fe255e3526c',
    messagingSenderId: '379493253637',
    projectId: 'wallia-market',
    storageBucket: 'wallia-market.appspot.com',
    iosClientId: '379493253637-49hcgp9tbdtuf6era2ah13uqqj2rrou9.apps.googleusercontent.com',
    iosBundleId: 'com.example.waliamarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZYTXRHSkws7PaRHSbaeWtnJ2Fv5mqs-o',
    appId: '1:379493253637:ios:5e986932621fe255e3526c',
    messagingSenderId: '379493253637',
    projectId: 'wallia-market',
    storageBucket: 'wallia-market.appspot.com',
    iosClientId: '379493253637-49hcgp9tbdtuf6era2ah13uqqj2rrou9.apps.googleusercontent.com',
    iosBundleId: 'com.example.waliamarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjW0qLj7eiijAsEgyWDqm1_ZpmZAto2_8',
    appId: '1:379493253637:web:5b2ae6505fdbcef1e3526c',
    messagingSenderId: '379493253637',
    projectId: 'wallia-market',
    authDomain: 'wallia-market.firebaseapp.com',
    storageBucket: 'wallia-market.appspot.com',
  );
}
